name: pdf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install wkthtmltopdf
        run: |
          sudo apt-get install -y xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
          
      - name: Install Liberation Fonts
        run: |
          sudo apt-get update -y
          sudo apt-get install -y fonts-liberation
          
      - name: Run .py script for Doc Generation
        run: |
          cmake . -Bbuild
          cmake --build build
          
      - name: Upload zipped doc file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/pdf.zip
          asset_name: PDF-Offline-Manual.zip
          tag: Docs-Release
          overwrite: true
          body: "This is a release containing the Docs Generated using Github Actions."
